---

- name: added in 2.4, previously you used 'include'
  import_tasks: redhat.yml
  when: ansible_os_platform|lower == 'redhat'

- import_tasks: ubuntu_18-04.yml
  when: ansible_os_family|lower == 'Ubuntu'